# Generated by Django 4.0.1 on 2022-01-16 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, verbose_name='identification code')),
                ('date_birth', models.DateTimeField(verbose_name='date of birthday')),
                ('breed', models.CharField(choices=[('AF', 'Afghan Hound'), ('PE', 'Pekingese'), ('BA', 'Bassador')], max_length=100, verbose_name='animal species')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('partners', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodline_api.dog', verbose_name='related partners')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related user')),
            ],
        ),
    ]
