# Generated by Django 4.0.1 on 2022-01-18 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline_api', '0004_remove_dog_partners_dog_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='user',
        ),
        migrations.AddField(
            model_name='dog',
            name='litters',
            field=models.ManyToManyField(blank=True, to='bloodline_api.Dog', verbose_name='related litters'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='related user'),
        ),
        migrations.AddField(
            model_name='dog',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='bloodline_api.Dog', verbose_name='related siblings'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('AF', 'Afghan Hound'), ('PE', 'Pekingese'), ('BA', 'Bassador')], max_length=2, verbose_name='animal species'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='identification code'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
    ]
