#
# Dog http request
#

### Get all dogs
GET http://127.0.0.1:8000/dogs/ HTTP/1.1
content-type: application/json
accept: application/json

### Create a dog
POST http://127.0.0.1:8000/dogs/ HTTP/1.1
content-type: application/json
accept: application/json
Authorization: Token ff99e73fca40d6b977081b9d1f11932cb3439785

{
  "name": "B",
  "code": "22222",
  "date_birth": "2022-01-02T07:09:51Z",
  "breed": "BA"
}

### Get a dog
GET http://127.0.0.1:8000/dogs/31/ HTTP/1.1
content-type: application/json
accept: application/json

### Update a dog
PUT http://127.0.0.1:8000/dogs/35/ HTTP/1.1
content-type: application/json
accept: application/json
Authorization: Token ff99e73fca40d6b977081b9d1f11932cb3439785

{
  "name": "C",
  "code": "66666",
  "date_birth": "2022-01-16T07:09:51Z",
  "owner": 5,
  "breed": "BA",
  "partners": [],
  "litters": [],
  "siblings": []
}

### Delete a dog
DELETE http://127.0.0.1:8000/dogs/31/ HTTP/1.1
content-type: application/json
accept: application/json
Authorization: Token ff99e73fca40d6b977081b9d1f11932cb3439785